title: Sagar Sahani
baseurl: ''
desc: Java, Python, Algorithm, Data Structures, Node.JS, REST APIs, MVC, SQL, Elasticsearch, AWS
about: >-
  Software engineering 🎓 recent graduate with an emphasis in backend programming, algorithm & data structures, and OOP.
image: >-
  https://media-exp1.licdn.com/dms/image/C4D03AQEg5pplrkIolQ/profile-displayphoto-shrink_800_800/0/1623961610299?e=1636588800&v=beta&t=0oKH73HzU6m1jldKuSumE6FfgPwmhd3HtMG7WvQznqQ
excerpt_separator: <!-- more -->
markdown: kramdown
gems: [jekyll-paginate]
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: '/:num/'
highlighter: rouge
permalink: pretty
url: ''
